spring:
  config:
    import: application-common.yml
  cloud:
    gateway:
      default-filters:
        - SetRequestHeader=X-Forwarded-Proto, https
      routes:
        - id: exchange-service
          uri: https://exchange-dev.kwt.co.kr
          predicates:
            - Path=/exchange/**
          filters:
            - RewritePath=/exchange/(?<segment>.*), /${segment}
            - name: RequestLogging
            - name: ResponseLogging

        - id: salary-service
          uri: https://salary-dev.kwt.co.kr
          predicates:
            - Path=/salary/**
          filters:
            - RewritePath=/salary/(?<segment>.*), /${segment}
            - name: RequestLogging
            - name: ResponseLogging
  data:
    redis:
      host: redis-master.kwt-dev.svc.cluster.local
      port: 6379
      password: fpeltmWkd!@#123
      database: 0

logging:
  level:
    root: INFO
    kr.co.kwt.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty.http.client: DEBUG

gateway:
  rate-limit:
    default-config:
      capacity: 100
      refill-tokens: 10
      refill-period: 1s
      user:
        capacity: 200
        refill-tokens: 20
      api:
        capacity: 150
        refill-tokens: 15
      ip:
        capacity: 50
        refill-tokens: 5
    routes:
      api-service:
        capacity: 200
        refill-tokens: 20
        refill-period: 1s
        user:
          capacity: 300
          refill-tokens: 30
        api:
          capacity: 250
          refill-tokens: 25
        ip:
          capacity: 100
          refill-tokens: 10