server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

gateway:
  security:
    allowed-domains:
      - localhost
      - kwt.co.kr
      - kwt-dev.co.kr
    public-paths:
      - /public/**
      - /auth/login
      - /auth/register
  cors:
    allowed-origins:
      - https://*.kwt.co.kr
      - https://*.kwt-dev.co.kr
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers:
      - "*"
    max-age: 3600